<?php 
	if(!$this->session->userdata('user_email')):
        $this->load->view('admin/login_page'); 
    else:    	    	
    	$user_type=$this->session->userdata('user_type');
		if(!isset($page)){
			$page=$user_type.'/common/dashboard';
		}
		$base_folder=explode("/",$page);		
		if($user_type==$base_folder[0]){
			$this->load->view($user_type.'/common/header');
			$this->load->view($user_type.'/common/menu');
			$this->load->view($page);
			$this->load->view($user_type.'/common/footer');			
		}else{
			redirect('admin/'.$user_type);
		}
	endif;
 ?>